### ISSUE TITLE
Feature: add select2 to all fields

### ISSUE THREAD

**Issue by kty0mka** [AlphaNodes/additionals#62]
First of all, thank you for the useful plugin!
We started using it, especially features such as hide members of some roles, go to top, freeze closed issues, external urls in new tabs and menu customization.

We also use the [Select to Select 2](https://github.com/sf-cola/select_to_select2) plugin, which adds Select2 to all fields (standard and custom). For us, this is an indispensable function, because some of our custom fields have a huge list of possible values with long names of values and I can not imagine how our customers will select these values from the list without the search that select2 provides.

Unfortunately, Select to Select 2 breaks in the Additionals the function of changing the author of the task, which we also really need (previously we used the [redmine_editauthor](https://github.com/rgtk/redmine_editauthor) plugin, which cannot be installed simultaneously with Additionals).
Yes, I understand that it is the Select to Select 2 plugin creates the problem. It is buggy by itself, it uses the old Select2 library, breaks the custom fields choice when writing formulas in the [Computed Custom Field plugin](https://github.com/annikoff/redmine_plugin_computed_custom_field) (we turning off select_to_select2 during the creation of custom fileds), violates performance during Worflows editing if there are a lot of Custom Fields is used with the tracker, distorts the choice in the fields of the [CKE plugin](https://github.com/a-ono/redmine_ckeditor), and probably spoils a lot more.

And here is what I thought. If I understand correctly, the Additionals - is a plugin with many small general-purpose improvements for Redmine, right? Can you then consider adding functionality similar to Select to Select 2 in Additionals? You already have a Select2 library built-in) The function could be enabled optionally in the Additionals settings or even individually enabled for each field and query pages. It seems to me that a more convenient choice from fields with many values is something that can be useful to a very wide range of users in a variety of scenarios.

**Comment by tainewoo** [comment]
Hi @kty0mka ,
i happed to have a fork of the select to select2 plugin which i modified most of the codes, u can have a try.
https://github.com/tainewoo/select_to_select2
actually there are different situations to consider to change the select to select2 for Redmine and that’s why there would be lots of problems, and i tried to solve some of the bugs i met.
because i made too many changes, the behavior is not totally the same to the original one, and also using different version of Select2, so i didn’t port the changes back and only keep it there if someone wants to use the different one.

**Comment by alexandermeindl** [comment]
This feature will not integrated to additionals plugin.
