### ISSUE TITLE
How to restore the redmine default Dashboard?

### ISSUE THREAD

**Issue by uart-aplex** [AlphaNodes/additionals#83]
It seems the dashboard edit cannot undo, In case it gets messed up, how can I restore the original dashboard for re-editing?

**Comment by ClaudiaMeindl** [comment]
There is no Dashboard restore option. As soon as you edit a dashboard you change it. Take a look at the help on dashboards how to handle it: https://additionals.readthedocs.io/en/latest/dashboards/#

The recommended procedure is not to edit the existing "default", but to create a new dashboard and make your changes there. If everything is correct, this will be marked as the new "default" dashboard. So you always have the old one as a "backup" in case you need it.

**Comment by uart-aplex** [comment]
Understood, and it is a bad news for someone like me, I have messed up the default dashboard, I hope that in the future there will be the function of restoring the default dashboard, or a warning to backup default dashboard so as not to have other people like me, I don't know that there is no undo function before I start to use it.

**Comment by ClaudiaMeindl** [comment]
Thanks for getting back. There is nothing bad about it.
You just delete the dashboard blocks you don't like and add others instead. A restore function doesn't do anything else either. 
The plugin even comes with a help (in opposite to a lot of other plugins). It's always best to read it, especially if you are not sure what to do.

**Comment by uart-aplex** [comment]
Deleting or moving a block does not mean that I don’t need the original anymore. I did these actions because I don’t want some messages to be seen by customers in a certain project, such as Members, but for other projects are used internally then I want to keep it as it is, But I didn't expect that after I changed it in a project, it would affect the dashboard of the entire system and could not be restored.

**Comment by ClaudiaMeindl** [comment]
The content that a user sees in the dashboard is related to the permissions assigned to their given role. They must be set correctly before you try to control this via the dashboard blocks.

For example, if you want to hide the "Members" of a specific role you may not control this via the "Dashboard" block, but via "Roles and Permissions" in the administration area: https://additionals.readthedocs.io/en/latest/manual/#additionals-permissions

Of course, this only works as long as the user is not assigned to multiple roles that cancel each other out
Dashboard blocks with manually stored content are also an exception to this rule, because manual content can be seen by everyone.

**Comment by uart-aplex** [comment]
If I uninstall this plugin, does the system default dashboard will be restored?

**Comment by ClaudiaMeindl** [comment]
If the plugin uninstallation guide is used (https://github.com/AlphaNodes/additionals#uninstall), the data (in this case stored dashboards) are gone. If you remove it manually, than no.

**Comment by uart-aplex** [comment]
Does "The data (in this case stored dashboards) are gone. "  means my newly created dashboard or the original system default dashboard gone? I don't mind the newly created dashboard, I just want to get back the original system default dashboard.

Sorry to bother you a lot, I should try it on the server used for local testing first, not directly with the online server.

**Comment by ClaudiaMeindl** [comment]
The system default should be restored, the rest will be deleted when uninstalling. If you are insecure how to handle the function, you should probably set up a test system to check things out. In my opinion it's actually easier to create the default dashboard manually instead of re-installing a plugin. 

The standard blocks (project overview) are only a handful that you have to set up. It's not tricky at all. See documentation update on default dashboard blocks: https://additionals.readthedocs.io/en/latest/dashboards/#default-dashboards

**Comment by uart-aplex** [comment]
Another issue for me want to remove additionals plugin, because it conflicts with the Easy Gantt plugin PRO(Commercial version), once installed additionals into redmine, then I cannot add issue from the Easy Gantt's interface anymore.

**Comment by alexandermeindl** [comment]
Use the uninstall documentation to remove additionals plugin: https://github.com/AlphaNodes/additionals#uninstall
After this, your Redmine has no more changes from additionals plugin. If you have any problem after uninstall this plugin, you should request help for support of Easy Redmine producers.
