### ISSUE TITLE
Question - Redmine 4.0 support

### ISSUE THREAD

**Issue by sseide** [AlphaNodes/additionals#88]
Hello, 
i like to ask why support for Redmine 4.0 was dropped as this is a official supported version available from redmine.org.
Are there any reasons for this?
And some distributions provide packages of Redmine 4.0 only, no 4.1 versions (Debian / Ubuntu). With them its now impossible to use latest "additionals" plugin.

And asked that i like to ask for support of Redmine 4.0 by current verison of the plugin.

Thanks in advance,
Stefan

**Comment by alexandermeindl** [comment]
Hi Stefan,
with additionals 3.0 we implemented dashboard functionality. Because it would be a lot more complex to support 4.0 with this, we dropped it. We spent a lot of time (3 month) to get dashboard functionality to addtionals - 2 month more, as we planed ;) Because of complexity there is no chance to get Redmine 4.0 support again.

**Comment by sseide** [comment]
Ok - understand.

Than i have only one request - please backport security related fixes to the 2.x line as long as Redmine 4.0 is offical supported. Than its save to use as some other plugins require your plugin (without the Dashboard feature).

Maintaining systems is much less time-consuming having os packages for as much as possible and no need to update everything manually (as why deb packages are used for Redmine)...

Thanks in advance,
Stefan

**Comment by alexandermeindl** [comment]
Redmine 4.x is not supported with next release. Only Redmine 5.x will be maintained.
